/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as JoinRouteImport } from './routes/join'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as ResearchHigherEducationRouteImport } from './routes/research.higher-education'
import { Route as ResearchK12RouteImport } from './routes/research.k12'
import { Route as ResearchProfessionalsRouteImport } from './routes/research.professionals'
import { Route as ResearchThirdAgeRouteImport } from './routes/research.third-age'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResearchRoute,
} as any)
const ResearchHigherEducationRoute = ResearchHigherEducationRouteImport.update({
  id: '/higher-education',
  path: '/higher-education',
  getParentRoute: () => ResearchRoute,
} as any)
const ResearchK12Route = ResearchK12RouteImport.update({
  id: '/k12',
  path: '/k12',
  getParentRoute: () => ResearchRoute,
} as any)
const ResearchProfessionalsRoute = ResearchProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => ResearchRoute,
} as any)
const ResearchThirdAgeRoute = ResearchThirdAgeRouteImport.update({
  id: '/third-age',
  path: '/third-age',
  getParentRoute: () => ResearchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/news': typeof NewsRoute
  '/people': typeof PeopleRoute
  '/platform': typeof PlatformRoute
  '/research': typeof ResearchRouteWithChildren
  '/research/higher-education': typeof ResearchHigherEducationRoute
  '/research/k12': typeof ResearchK12Route
  '/research/professionals': typeof ResearchProfessionalsRoute
  '/research/third-age': typeof ResearchThirdAgeRoute
  '/research/': typeof ResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/news': typeof NewsRoute
  '/people': typeof PeopleRoute
  '/platform': typeof PlatformRoute
  '/research/higher-education': typeof ResearchHigherEducationRoute
  '/research/k12': typeof ResearchK12Route
  '/research/professionals': typeof ResearchProfessionalsRoute
  '/research/third-age': typeof ResearchThirdAgeRoute
  '/research': typeof ResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/news': typeof NewsRoute
  '/people': typeof PeopleRoute
  '/platform': typeof PlatformRoute
  '/research': typeof ResearchRouteWithChildren
  '/research/higher-education': typeof ResearchHigherEducationRoute
  '/research/k12': typeof ResearchK12Route
  '/research/professionals': typeof ResearchProfessionalsRoute
  '/research/third-age': typeof ResearchThirdAgeRoute
  '/research/': typeof ResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisory'
    | '/contact'
    | '/join'
    | '/news'
    | '/people'
    | '/platform'
    | '/research'
    | '/research/higher-education'
    | '/research/k12'
    | '/research/professionals'
    | '/research/third-age'
    | '/research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisory'
    | '/contact'
    | '/join'
    | '/news'
    | '/people'
    | '/platform'
    | '/research/higher-education'
    | '/research/k12'
    | '/research/professionals'
    | '/research/third-age'
    | '/research'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisory'
    | '/contact'
    | '/join'
    | '/news'
    | '/people'
    | '/platform'
    | '/research'
    | '/research/higher-education'
    | '/research/k12'
    | '/research/professionals'
    | '/research/third-age'
    | '/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisoryRoute: typeof AdvisoryRoute
  ContactRoute: typeof ContactRoute
  JoinRoute: typeof JoinRoute
  NewsRoute: typeof NewsRoute
  PeopleRoute: typeof PeopleRoute
  PlatformRoute: typeof PlatformRoute
  ResearchRoute: typeof ResearchRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/research/higher-education': {
      id: '/research/higher-education'
      path: '/higher-education'
      fullPath: '/research/higher-education'
      preLoaderRoute: typeof ResearchHigherEducationRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/research/k12': {
      id: '/research/k12'
      path: '/k12'
      fullPath: '/research/k12'
      preLoaderRoute: typeof ResearchK12RouteImport
      parentRoute: typeof ResearchRoute
    }
    '/research/professionals': {
      id: '/research/professionals'
      path: '/professionals'
      fullPath: '/research/professionals'
      preLoaderRoute: typeof ResearchProfessionalsRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/research/third-age': {
      id: '/research/third-age'
      path: '/third-age'
      fullPath: '/research/third-age'
      preLoaderRoute: typeof ResearchThirdAgeRouteImport
      parentRoute: typeof ResearchRoute
    }
  }
}

interface ResearchRouteChildren {
  ResearchHigherEducationRoute: typeof ResearchHigherEducationRoute
  ResearchK12Route: typeof ResearchK12Route
  ResearchProfessionalsRoute: typeof ResearchProfessionalsRoute
  ResearchThirdAgeRoute: typeof ResearchThirdAgeRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchHigherEducationRoute: ResearchHigherEducationRoute,
  ResearchK12Route: ResearchK12Route,
  ResearchProfessionalsRoute: ResearchProfessionalsRoute,
  ResearchThirdAgeRoute: ResearchThirdAgeRoute,
  ResearchIndexRoute: ResearchIndexRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisoryRoute: AdvisoryRoute,
  ContactRoute: ContactRoute,
  JoinRoute: JoinRoute,
  NewsRoute: NewsRoute,
  PeopleRoute: PeopleRoute,
  PlatformRoute: PlatformRoute,
  ResearchRoute: ResearchRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
